language: haxe

sudo: false

haxe:
  - "4.0.2"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install hxnodejs
  - haxelib dev hxnodejs-sqlite3 .

script:
  - haxe haxedoc.hxml
  - haxe --cwd example/ build.hxml
