name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1.4.0
        with:
          haxe-version: 4.2.5
      - name: Setup
        run: |
          haxe --version
          haxelib dev hxnodejs-sqlite3 .
          haxelib install hxnodejs
      - name: Build haxedoc.xml
        run: haxe haxedoc.hxml
      - name: Example application
        run: |
          cd example
          npm install
          npm run build
          npm start 
